# Generated by Django 6.0.5 on 2026-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('target', models.IntegerField(default=0)),
                ('current_run_rate', models.FloatField(default=0.0)),
                ('score_history', models.JSONField(default=list)),
                ('recent_balls', models.JSONField(default=list)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
    ]
