# Generated by Django 6.0.5 on 2026-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_url',
            field=models.URLField(default='http://localhost:8080/hls/ankit1.m3u8', max_length=500),
        ),
    ]
