# Generated by Django 6.0.5 on 2026-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('LIVE_SPORTS', 'Live Sports'), ('TRENDING_MOVIES', 'Trending Movies'), ('TOP_WEB_SERIES', 'Top Web Series'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
