# Generated by Django 6.0.5 on 2026-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
