# Generated by Django 6.0.5 on 2026-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
