# Generated by Django 6.0.5 on 2026-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_embed_code_match_imdb_id_match_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('LIVE_SPORTS', 'Live Sports'), ('TRENDING_MOVIES', 'Trending Movies'), ('BHOJPURI_HITS', 'Bhojpuri Hits'), ('SOUTH_HINDI', 'South Indian Hindi'), ('TOP_WEB_SERIES', 'Top Web Series'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
