# Generated by Django 6.0.5 on 2026-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='recent_balls',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Recent balls'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_history',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Score history'),
        ),
    ]
