# Generated by Django 6.0.5 on 2026-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_recent_balls_alter_match_score_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
