# Generated by Django 6.0.5 on 2026-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status_text',
            field=models.CharField(blank=True, default='Live Match Session', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='server_2_link',
            field=models.CharField(blank=True, help_text='Server 2 Link (e.g., English)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_3_link',
            field=models.CharField(blank=True, help_text='Server 3 Link (Backup)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_4_link',
            field=models.CharField(blank=True, help_text='Server 4 Link (Backup)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_5_link',
            field=models.CharField(blank=True, help_text='Server 5 Link (Backup)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_6_link',
            field=models.CharField(blank=True, help_text='Server 6 Link (Backup)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.CharField(blank=True, default='0/0', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.CharField(blank=True, default='Yet to Bat', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.CharField(blank=True, default='International Series', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, default='Live Stadium', max_length=150),
        ),
        migrations.AlterField(
            model_name='match',
            name='live_link',
            field=models.CharField(default='', help_text='Default Server 1 Link (e.g., Hindi HD)', max_length=500),
            preserve_default=False,
        ),
    ]
