# Generated by Django 6.0.5 on 2026-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_match_status_text_match_server_2_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_1_badge',
            field=models.CharField(default='HINDI HD', help_text='Badge text for Server 1', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_1_name',
            field=models.CharField(default='Server 1', help_text='Button text for Server 1', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='server_2_badge',
            field=models.CharField(default='ENGLISH', help_text='Badge text for Server 2', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_2_name',
            field=models.CharField(default='Server 2', help_text='Button text for Server 2', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='server_3_badge',
            field=models.CharField(default='ENGLISH CLOUD', help_text='Badge text for Server 3', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_3_name',
            field=models.CharField(default='Server 3', help_text='Button text for Server 3', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='server_4_badge',
            field=models.CharField(default='WILLOW 1', help_text='Badge text for Server 4', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_4_name',
            field=models.CharField(default='Server 4', help_text='Button text for Server 4', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='server_5_badge',
            field=models.CharField(default='WILLOW 2', help_text='Badge text for Server 5', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_5_name',
            field=models.CharField(default='Server 5', help_text='Button text for Server 5', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='server_6_badge',
            field=models.CharField(default='EMERGENCY BACKUP', help_text='Badge text for Server 6', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='server_6_name',
            field=models.CharField(default='Server 6', help_text='Button text for Server 6', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='live_link',
            field=models.CharField(default='', help_text='Default Server 1 Link (e.g., Hindi HD)', max_length=500),
        ),
    ]
