# Generated by Django 6.0.5 on 2026-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_match_date_match_match_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_type',
            field=models.CharField(choices=[('iframe', 'Iframe Link'), ('m3u8', 'Direct Stream')], default='iframe', max_length=10),
        ),
    ]
