# Generated by Django 6.0.5 on 2026-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('LIVE_SPORTS', 'Live Sports'), ('movie', 'Movies'), ('anime', 'Anime'), ('kids', 'Kids/Cartoons'), ('TRENDING_MOVIES', 'Trending Movies (Legacy)'), ('BHOJPURI_HITS', 'Bhojpuri Hits (Legacy)'), ('SOUTH_HINDI', 'South Indian Hindi (Legacy)'), ('TOP_WEB_SERIES', 'Top Web Series (Legacy)'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
