# Generated by Django 6.0.5 on 2026-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_match_download_url_match_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='server2_url',
            field=models.CharField(blank=True, help_text='Streaming/Embed Link (e.g. Speedostream)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
