# Generated by Django 6.0.5 on 2026-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_match_server2_url_match_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('movie', 'Movies'), ('web_series', 'Web Series'), ('hindi_series', 'Hindi Series'), ('hot_series', 'Hot Series')], default='OTHERS', max_length=50),
        ),
    ]
